# Site settings
title: Kelvin Tan Yeow Boon
email: kelvin.tyb@gmail.com
url: https://kelvintyb.github.io
description: "Portfolio site for Kelvin Tan Yeow Boon - Full Stack Web Developer."
skills: "Web Developer - Cat Lover - Former Space Man"
meta_author: Tan Kelvin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2F131E #6D72C3
  primary-rgb: "109,114,195" #"128,179,255"
  secondary: 2C365E #5941A9
  secondary-dark: 514F59 #2F131E

# Footer settings
footer:
  copyright: Kelvin Tan Yeow Boon
  location: Location
  social: Get in Touch
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kelvintanyb
  - title: github
    url: http://github.com/kelvintyb
  - title: envelope-o
    url: mailto:kelvin.tyb@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Mostly traipsing around the East of Singapore

# Credits content
credits: 'Built on top of Freelancer - a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
